In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [5]:
movies = pd.read_csv('movies.csv')

In [21]:
movies['status'] = movies['status'].replace('Realesed', '1')
movies['status'] = movies['status'].replace('Post Production', '2')
movies['status'] = movies['status'].replace('Rumored', '3')

In [22]:
movies.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [23]:
# Pilih fitur dan target
X = movies.drop(columns=['index','original_language', 'original_title', 'overview', 'production_companies', 'production_countries', 'spoken_languages', 'title', '' 'homepage', 'id', 'keywords', 'tagline', 'release_date', 'director', 'cast', 'crew', 'genres'])  # Ganti 'target_column' dengan nama kolom target
y = movies['status']

In [24]:
X

budget  popularity     revenue  runtime    status  vote_average  \
0     237000000  150.437577  2787965087    162.0  Released           7.2   
1     300000000  139.082615   961000000    169.0  Released           6.9   
2     245000000  107.376788   880674609    148.0  Released           6.3   
3     250000000  112.312950  1084939099    165.0  Released           7.6   
4     260000000   43.926995   284139100    132.0  Released           6.1   
...         ...         ...         ...      ...       ...           ...   
4798     220000   14.269792     2040920     81.0  Released           6.6   
4799       9000    0.642552           0     85.0  Released           5.9   
4800          0    1.444476           0    120.0  Released           7.0   
4801          0    0.857008           0     98.0  Released           5.7   
4802          0    1.929883           0     90.0  Released           6.3   

      vote_count  
0          11800  
1           4500  
2           4466  
3           9106  
4           2124  
...          ...  
4798         238  
4799           5  
4800           6  
4801           7  
4802          16  

[4803 rows x 7 columns]

In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([2, 2, 2, ..., 2, 2, 2])

In [26]:
X

budget  popularity     revenue  runtime    status  vote_average  \
0     237000000  150.437577  2787965087    162.0  Released           7.2   
1     300000000  139.082615   961000000    169.0  Released           6.9   
2     245000000  107.376788   880674609    148.0  Released           6.3   
3     250000000  112.312950  1084939099    165.0  Released           7.6   
4     260000000   43.926995   284139100    132.0  Released           6.1   
...         ...         ...         ...      ...       ...           ...   
4798     220000   14.269792     2040920     81.0  Released           6.6   
4799       9000    0.642552           0     85.0  Released           5.9   
4800          0    1.444476           0    120.0  Released           7.0   
4801          0    0.857008           0     98.0  Released           5.7   
4802          0    1.929883           0     90.0  Released           6.3   

      vote_count  
0          11800  
1           4500  
2           4466  
3           9106  
4           2124  
...          ...  
4798         238  
4799           5  
4800           6  
4801           7  
4802          16  

[4803 rows x 7 columns]

In [28]:
y

array([2, 2, 2, ..., 2, 2, 2])

In [11]:
kolom_yang_pilih = 'status'

# Menampilkan isi dari kolom yang dipilih
print(movies[kolom_yang_pilih])


0       Released
1       Released
2       Released
3       Released
4       Released
          ...   
4798    Released
4799    Released
4800    Released
4801    Released
4802    Released
Name: status, Length: 4803, dtype: object


In [12]:
y

array([1, 1, 1, ..., 1, 1, 1])

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [17]:
model = GaussianNB()
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'Released'